---@brief
--- https://github.com/tailwindlabs/tailwindcss-intellisense
---
--- Tailwind CSS Language Server can be installed via npm:
---
--- npm install -g @tailwindcss/language-server
return {
	cmd = { 'tailwindcss-language-server', '--stdio' },
	-- filetypes copied and adjusted from tailwindcss-intellisense
	filetypes = {
		'aspnetcorerazor',
		'astro',
		'astro-markdown',
		'blade',
		'clojure',
		'django-html',
		'htmldjango',
		'edge',
		'eelixir',
		'elixir',
		'ejs',
		'erb',
		'eruby',
		'gohtml',
		'gohtmltmpl',
		'haml',
		'handlebars',
		'hbs',
		'html',
		'htmlangular',
		'html-eex',
		'heex',
		'jade',
		'leaf',
		'liquid',
		'markdown',
		'mdx',
		'mustache',
		'njk',
		'nunjucks',
		'php',
		'razor',
		'slim',
		'twig',
		'css',
		'less',
		'postcss',
		'sass',
		'scss',
		'stylus',
		'sugarss',
		'javascript',
		'javascriptreact',
		'reason',
		'rescript',
		'typescript',
		'typescriptreact',
		'vue',
		'svelte',
		'templ',
	},
	settings = {
		tailwindCSS = {
			validate = true,
			lint = {
				cssConflict = 'warning',
				invalidApply = 'error',
				invalidScreen = 'error',
				invalidVariant = 'error',
				invalidConfigPath = 'error',
				invalidTailwindDirective = 'error',
				recommendedVariantOrder = 'warning',
			},
			classAttributes = {
				'class',
				'className',
				'class:list',
				'classList',
				'ngClass',
			},
			includeLanguages = {
				eelixir = 'html-eex',
				elixir = 'phoenix-heex',
				eruby = 'erb',
				heex = 'phoenix-heex',
				htmlangular = 'html',
				templ = 'html',
			},
		},
	},
	workspace_required = true,
	root_markers = { ".git" }
}
